### PR TITLE
support setting a single-variable objective by promoting to ScalarAffineFunction

### PR DESCRIPTION
**Pull request by rdeits**

### CODE REVIEW

**Comment by odow** [comment]
I just got to my office and was about to have a look at this. 

It also needs `canset`, `canget`, `get`, and probably `canmodifyobjective = false`.

**Comment by rdeits** [comment]
Ok, I'll see what I can do.

**Comment by odow** [comment]
Actually, you probably can modify the objective, but then it turns into a `ScalarAffineFunction`. 

You could change https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/ce60996abb3b8c8b6b471968bf5159b98b7e0abd/src/LinQuadOptInterface.jl#L148 to an enum to say whether it is affine, quadratic, or single variable.

**Comment by rdeits** [comment]
I think `canset` is already handled correctly here, assuming the solvers are defining `supported_objectives`: https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/ce60996abb3b8c8b6b471968bf5159b98b7e0abd/src/objective.jl#L36

**Comment by rdeits** [comment]
Ok

**Comment by rdeits** [comment]
Actually, I'm not sure the enum is necessary, if I'm promoting the single variable to ScalarAffine as soon as it's `set!()`. 

I guess there are two ways of implementing this: 

1. `set!(..., ::SinVar)` automatically constructs a `Linear` and then calls `set!()` with that. In that case, the objective is indistinguishable from a `Linear` objective, so only `canget(..., ::Linear)` will work.

2. `set!(..., ::SinVar)` actually sets the objective enum to `SingleVariable`, and `canget(..., ::SinVar)` returns `true`. I assume we'd still implement setting the objective by using the existing `set_linear_objective!`. To `get(..., ::SinVar)` we'd have to call `get_linear_objective!()` and then, I guess, scan through the resulting coefficients to find the one nonzero?

**Comment by odow** [comment]
I guess it depends how truthful we want to be to the API.

It's probably fine to say that `min x` is actually `min 1.0x` an that we only support affine and quadratic objectives (since that is what the solvers support). It just needs to be documented.

**Comment by rdeits** [comment]
Ok, I've implemented the enum version. Modifying the objective will convert it from single variable to affine.

**Comment by odow** [comment]
[Oarsome](https://www.youtube.com/watch?v=YaIZF8uUTtk), thanks!

**Pull request merged**
