### PR TITLE
RFC: updates for MOI 0.5

### PR DESCRIPTION
**Pull request by odow**
This PR begins to implement https://github.com/JuliaOpt/MathOptInterface.jl/pull/436

### Test status

<s>Tests are currently failing but at least it compiles.</s>
Can't test v0.7 because how do I checkout MOI master?

### Thoughts so far:
- [x] Should there be a general exception? What should I throw when someone goes:
```julia
MOI.get(m, MOI.VariableIndex, "name_doesnt_exist")
```
- [x] Who is responsible for throwing errors? MOI? LQOI? Solvers?
- [x] I almost always want to provide a string with additional information. The cachingoptimizer can look at the type, but users will want a string.
- [x] LQOI needs a clean

### TODO

- [x] Fix travis (currently checking out MOI master)
- [ ] Change MOI require bound

cc @blegat

### CODE REVIEW

**Comment by mlubin** [comment]
> Should there be a general exception?
 
`error` seems to be okay for this case if it's an exception that should always go back to the user and doesn't need to be handled programatically.

> Who is responsible for throwing errors? MOI? LQOI? Solvers?

All of the above. Users of an API should see errors that pertain directly to the operation that they called the API for and explain what they did wrong. This applies at all levels, so sometimes an error should be rethrown by a wrapper with a more precise or extended message.

>  I almost always want to provide a string with additional information. 

I agree. All the error types should allow you to provide an error message.

**Comment by odow** [comment]
Okay so my PR's to [GLPK](https://github.com/JuliaOpt/GLPK.jl/pull/59) and [Gurobi](https://github.com/JuliaOpt/Gurobi.jl/pull/146) are passing tests with this branch.

**Comment by mlubin** [comment]
> Even `UnsupportedError`s ?

Yes, why not?

**Comment by blegat** [comment]
> Yes, why not?

There is nothing much to say when you do not supports some type of constraints for instance.

**Comment by mlubin** [comment]
> There is nothing much to say when you do not supports some type of constraints for instance.

We can let the exception thrower decide about that. Maybe there's useful information like "you may want to try doing X instead".

**Pull request merged**
