### PR TITLE
fix handling of empty rows in vector affine functions

### LINKED ISSUE #48: Uninitialized data when handling vector functions with empty rows
Adding a `VectorAffineFunction` constraint to a model can cause uninitialized memory issues if that affine function has any empty rows (rows for which there is no `VectorAffineTerm`. I think the logic here isn't quite right: https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/e19c941b8005eb35d3b5d658fed40a63f12067ed/src/constraints/vectoraffine.jl#L36-L46 . When a row has no corresponding term, `row_pointers` is not set correctly, and the last element in `row_pointers` will just be left as `undef` (in this case, a random uninitialized `Int`). 

Here's a simple case to reproduce the issue: 

```julia
using Gurobi
using MathOptInterface
const MOI = MathOptInterface

model = GurobiOptimizer()
x = MOI.addvariables!(model, 1)
MOI.addconstraint!(model, 
    MOI.VectorAffineFunction(
        MOI.VectorAffineTerm.(2, MOI.ScalarAffineTerm.([1.0], x)),
        zeros(2)
    ), 
    MOI.Nonnegatives(2)
)
```

Running the above will either produce a Gurobi error code 10018 ("problem adding constraints") or an `InexactError()`, with the behavior varying based on whatever the uninitialized memory ended up as.

### PR DESCRIPTION
**Pull request by rdeits**
fixes #48

### CODE REVIEW

**Comment by rdeits** [comment]
Test added in https://github.com/JuliaOpt/MathOptInterface.jl/pull/457

**Comment by odow** [comment]
Is this good to merge? Then I can update the tag.

**Comment by odow** [comment]
Thanks @rdeits. I added the code to the case of adding multiple scalar affine functions which just demonstrates why LQOI shouldn't be doing the VectorAffine case.

**Comment by odow** [comment]
I've updated the tag so this will make it into the versions of GLPK and Gurobi I'm about to release.

**Pull request merged**
