### PR TITLE
Allow bounds with binary variable

### PR DESCRIPTION
**Pull request by odow**
Ref the discussion in https://github.com/JuliaOpt/Gurobi.jl/issues/195

### CODE REVIEW

**Comment by ExpandingMan** [comment]
Just to add to this: originally I thought the error was popping up as the result of some matrix multiplications where, just by random chance, I was winding up with some cases like `x ≤ 1`, however, on closer inspection, it looks like it's being caused somewhere else.

Regardless, the error is occurring as a result of some large-scale automatic generation of constraints, so it'd probably be a good idea to be fairly liberal with these checks so one doesn't not have too many special cases.

**Comment by mlubin** [comment]
I don't see why adding bounds on a binary variable should be an error. Do any solvers reject a problem where a binary variable is forced to equal 1 because of its bounds?

**Comment by ExpandingMan** [comment]
Just FYI, I've investigated this a little more and the only time I can get this to happen is if I do `set_lower_bound` or `set_upper_bound` explicitly on a binary variable.  Therefore, I walk back my previous comments a bit: I don't see much danger of this occurring without there being a simple remedy (if for example, some operations resulting in some `x ≤ 1` terms caused an error, that would obviously be a huge problem, but that doesn't seem to be happening here).

So, I still agree it's a good idea to drop this requirement, but it doesn't seem to be nearly as dangerous as I was originally thinking.

It is worth mentioning that if one gets the error, it is potentially extremely hard for users to track down, especially if they are not familiar with how JuMP works, because no error is thrown when the constraints are initially set.

**Comment by odow** [comment]
Closing in favor of #91

**Pull request closed without merging**
