### PR TITLE
Add quadratics and interval features

### PR DESCRIPTION
**Pull request by joaquimg**
related to #8

Should resolve:
 - get ConstraintSet of a ScalarAffineFunction-inInterval constraint.
 - get ConstraintSet of a ScalarQuadraticFunction constraint.
 - get ConstraintFunction of a ScalarQuadraticFunction constraint. 
 - get quadratic function

@odow

### CODE REVIEW

**Comment by odow** [comment]
LGTM. Tests?

**Comment by joaquimg** [comment]
The first three are in your unit tests already (via Xpress).
Do you have a unit get quadratic?
I have to work on the mock solver quadratic part.

**Comment by odow** [comment]
I'm going to merge this as-is and then bring Gurobi and GLPK up to date.

**Comment by joaquimg** [comment]
Nice! PR with tests coming soon, hopefully today.

**Pull request merged**
