### PR TITLE
Allow setting of duplicate variable and constraint names

### LINKED ISSUE #71: duplicate variable name failure
The behavior has changed with https://github.com/JuliaOpt/MathOptInterface.jl/pull/549
Running LQOI tests, I get:
```
Name test with LinQuadOptInterface.MockLinQuadOptimizer: Error During Test at /home/blegat/.julia/dev/MathOptInterface/src/Test/modellike.jl:7
  Got exception outside of a @test
  Duplicate variable name: Var1
  Stacktrace:
   [1] set(::LinQuadOptInterface.MockLinQuadOptimizer, ::MathOptInterface.VariableName, ::MathOptInterface.VariableIndex, ::String) at /home/blegat/.julia/dev/LinQuadOptInterface/src/variables.jl:38
   [2] macro expansion at /home/blegat/.julia/dev/MathOptInterface/src/Test/modellike.jl:29 [inlined]
   [3] macro expansion at /build/julia/src/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [4] nametest(::LinQuadOptInterface.MockLinQuadOptimizer) at /home/blegat/.julia/dev/MathOptInterface/src/Test/modellike.jl:8
   [5] macro expansion at /home/blegat/.julia/dev/LinQuadOptInterface/test/runtests.jl:30 [inlined]
   [6] macro expansion at /home/blegat/.julia/dev/LinQuadOptInterface/test/runtests.jl:17 [inlined]
   [7] macro expansion at /build/julia/src/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [8] macro expansion at /home/blegat/.julia/dev/LinQuadOptInterface/test/runtests.jl:16 [inlined]
   [9] macro expansion at /build/julia/src/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [10] top-level scope at /home/blegat/.julia/dev/LinQuadOptInterface/test/runtests.jl:11
┌ Warning: Constant in scalar function moved into set.
└ @ LinQuadOptInterface ~/.julia/dev/LinQuadOptInterface/src/constraints/scalaraffine.jl:44
┌ Warning: Constant in scalar function moved into set.
└ @ LinQuadOptInterface ~/.julia/dev/LinQuadOptInterface/src/constraints/scalaraffine.jl:44
Test Summary:                                                 | Pass  Error  Total
LinQuadOptInterface                                           | 1365      1   1366
  Unit Tests                                                  |  362           362
  Linear tests                                                |  513           513
  Quadratic tests                                             |  155           155
  Linear Conic tests                                          |  172           172
  Integer Linear tests                                        |   78            78
  ModelLike tests                                             |   85      1     86
    nametest                                                  |   11      1     12
      Name test with LinQuadOptInterface.MockLinQuadOptimizer |   11      1     12
    validtest                                                 |   10            10
    emptytest                                                 |   11            11
    orderedindicestest                                        |    9             9
    copytest                                                  |   44            44
ERROR: LoadError: Some tests did not pass: 1365 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/blegat/.julia/dev/LinQuadOptInterface/test/runtests.jl:10
```

### PR DESCRIPTION
**Pull request by odow**
Closes #71.

This PR needs a new tag of MOI to pass tests on travis, but is passing locally with the latest MOI master.

### CODE REVIEW

**Comment by odow** [comment]
We need the set of all variables of that name in case variables are renamed and a name is no longer duplicate.
```julia
x = MOI.add_variables(model, 2)
MOI.set(model, MOI.VariableName(), x[1], "x")
MOI.get(model, MOI.VariableIndex, "x")  == x[1]
MOI.set(model, MOI.VariableName(), x[2], "x")
MOI.get(model, MOI.VariableIndex, "x")  # errors
MOI.set(model, MOI.VariableName(), x[1], "y")
MOI.get(model, MOI.VariableIndex, "x")  == x[2]  # We need to remember for this case.
```

**Comment by joaquimg** [comment]
I would do just like a regular programming language once you repeat a name, the earlier variable with that name forgets it.
But that is ok.

**Comment by mlubin** [comment]
The reverse lookup dictionary (string to variable/constraint) is very expensive to maintain (https://github.com/JuliaOpt/JuMP.jl/issues/1402#issuecomment-427619730). In MOIU.Model the reverse maps are now built on demand only when a user does a lookup.

**Comment by blegat** [comment]
> This PR needs a new tag of MOI to pass tests on travis

That means that we wont be able to tag a non-breaking release of MOI as the metadata reverse dependency test will fail with LQOI. This is annoying. Can't we tag a LQOI release were name tests are commented out first ?

**Comment by mlubin** [comment]
> That means that we wont be able to tag a non-breaking release of MOI as the metadata reverse dependency test will fail with LQOI. This is annoying. Can't we tag a LQOI release were name tests are commented out first ?

Bump. Can we resolve this and get a new MOI release? There's a lot of good stuff on MOI `master`.

**Comment by odow** [comment]
I've disabled the name test. This will allow a new tag of MOI. I can come back and fix the reverse lookup this weekend.

**Pull request merged**
