### PR TITLE
make setting and getting the objective constant a part of the LQOI interface

### PR DESCRIPTION
**Pull request by rdeits**
First step for #43

### CODE REVIEW

**Comment by rdeits** [comment]
Gurobi.jl tests also pass for me with LQOI set to this branch.

**Comment by rdeits** [comment]
I tried updating Gurobi.jl to overload the functions introduced here by setting `ObjCon`, but i think I may have found a bug in Gurobi itself. While setting ObjCon before solving the model works once, further modifications to it have no effect on the objective value returned by later solves. You should be able to reproduce this without needing this particular branch: 

```julia
model = GurobiOptimizer();
MOI.empty!(model)
MOIU.loadfromstring!(model,"""
    variables: x
    maxobjective: 1.0x
    c1: 1.0x <= 1.0
""")
x = MOI.get(model, MOI.VariableIndex, "x")

Gurobi.set_dblattr(model.inner, "ObjCon", 1.0)  # this works
Gurobi.update_model!(model.inner)
MOI.optimize!(model)
# This assertion passes
@assert MOI.get(model, MOI.ObjectiveValue()) == 2.0  # (1.0 * 1.0 + 1.0)

Gurobi.set_dblattr(model.inner, "ObjCon", 2.0)  # this has no effect
Gurobi.update_model!(model.inner)
MOI.optimize!(model)
# This assertion fails:
@assert MOI.get(model, MOI.ObjectiveValue()) == 3.0  # (1.0 * 1.0 + 2.0)
```

**Comment by odow** [comment]
Do you have python/gurobipy installed? Otherwise I can have a look when I get back to my desk

**Comment by rdeits** [comment]
Yeah, I'm trying it in python now

**Comment by rdeits** [comment]
Hm, I'm not sure how to reproduce this in Python, since the API is totally different. I tried doing: 

```py
from __future__ import print_function
import gurobipy as grb

m = grb.Model("lp")
x = m.addVar(name="x")
obj = 1.0 * x + 1.0
m.setObjective(obj, sense=grb.GRB.MAXIMIZE)
m.addConstr(1.0 * x <= 1.0)
m.optimize()
print("objval:", m.getObjective().getValue())

m.setObjective(1.0 * x + 2.0)
m.optimize()
print("objval:", m.getObjective().getValue())
```

which works just fine, but that involves replacing the entire objective expression, which isn't what we're doing in Julia.

**Comment by rdeits** [comment]
In Julia, I get the correct result if I also set the `"Obj"` attribute (to the same value it had before):

```julia
model = GurobiOptimizer();
MOI.empty!(model)
MOIU.loadfromstring!(model,"""
    variables: x
    maxobjective: 1.0x
    c1: 1.0x <= 1.0
""")
x = MOI.get(model, MOI.VariableIndex, "x")

Gurobi.set_dblattr!(model.inner, "ObjCon", 1.0)  # this works
Gurobi.update_model!(model.inner)
MOI.optimize!(model)
# This assertion passes
@assert MOI.get(model, MOI.ObjectiveValue()) == 2.0  # (1.0 * 1.0 + 1.0)

Gurobi.set_dblattr!(model.inner, "ObjCon", 2.0)  # this has no effect
Gurobi.set_dblattrarray!(model.inner, "Obj", 1, 1, ones(1))
Gurobi.update_model!(model.inner)
MOI.optimize!(model)
@assert MOI.get(model, MOI.ObjectiveValue()) == 3.0  # (1.0 * 1.0 + 2.0)
```

**Comment by rdeits** [comment]
Ok, I can reproduce the issue in Python: 

```py
from __future__ import print_function
import gurobipy as grb

m = grb.Model("lp")
x = m.addVar(name="x")
obj = 1.0 * x + 1.0
m.setObjective(obj, sense=grb.GRB.MAXIMIZE)
m.addConstr(1.0 * x <= 1.0)
m.optimize()
print("ObjVal:", m.getAttr("ObjVal"))

m.setAttr("ObjCon", 2.0)
m.optimize()
print("ObjVal:", m.getAttr("ObjVal"))
```

**Comment by odow** [comment]
Have you sent them an issue (https://groups.google.com/forum/#!newtopic/gurobi)? Otherwise I'll do it now.

**Comment by rdeits** [comment]
I just did (but it looks like my message is still being held for moderation)

**Comment by odow** [comment]
Since @joaquimg is happy, would you like me to merge this now or wait for Gurobi?

**Comment by rdeits** [comment]
I'd say go ahead and merge. The issue with Gurobi is annoying but not related to this PR, and I think this is a good change nonetheless.

**Pull request merged**
